defaults:
  - model: cnn
  - loss: cross_entropy
  - optimizer: adam
  - scheduler: step_lr
  - augmentation: none
  - _self_

training:
  epochs: 30
  patience: 10
  verbose: true

data:
  batch_size: 64
  data_dir: "./data"
  debug_mode: true

wandb:
  project: "projet-framework-cifar10"
  run_name: "Test W&B"